class LifeOsError(Exception): ...
class NotionNotFound(LifeOsError): ...
class NotionAuthError(LifeOsError): ...
class TransientError(LifeOsError): ...
class WorkspaceUnavailable(LifeOsError): ...
class UnsupportedFieldType(LifeOsError): ...
